model_configs:
  volces_doubao:
    baseURL: https://ark.cn-beijing.volces.com/api/coding
    api_key: "{{ secrets.api_keys.volces }}"
    opus_model: "doubao-seed-2.0-code"
    sonnet_model: "doubao-seed-2.0-code"
    haiku_model: "doubao-seed-2.0-code"
    claude_code_subagent: "doubao-seed-2.0-code"
  volces_kimi_k2_5:
    baseURL: https://ark.cn-beijing.volces.com/api/coding
    api_key: "{{ secrets.api_keys.volces }}"
    opus_model: "kimi-k2.5"
    sonnet_model: "kimi-k2.5"
    haiku_model: "kimi-k2.5"
    claude_code_subagent: "kimi-k2.5"
  qiniu_claude:
    baseURL: https://openai.qiniu.com
    api_key: "{{ secrets.api_keys.qiniu_claude }}"
    opus_model: "claude-4.6-opus"
    sonnet_model: "claude-4.5-sonnet"
    haiku_model: "claude-4.6-haiku"
    claude_code_subagent: "claude-4.5-sonnet"
  qiniu_gpt_5_4:
    baseURL: https://openai.qiniu.com
    api_key: "{{ secrets.api_keys.qiniu_claude }}"
    opus_model: "openai/gpt-5.4"
    sonnet_model: "openai/gpt-5.4"
    haiku_model: "openai/gpt-5.4"
    claude_code_subagent: "openai/gpt-5.4"
  jdo_claude:
    baseURL: "https://api.ppio.com/anthropic"
    api_key: "{{ secrets.api_keys.jdo_key }}"
    opus_model: "pa/claude-opus-4-6"
    sonnet_model: "pa/claude-sonnet-4-5-20250929"
    haiku_model: "pa/claude-haiku-4-5-20251001"
    claude_code_subagent: "pa/claude-opus-4-6"

# use_model: "qiniu_claude"
use_model: "jdo_claude"
# use_model: "qiniu_claude"
# use_model: "volces_kimi_k2_5"
